# Credit Card Fraud Detection Configuration

# Data Configuration
data:
  raw_data_path: "data/raw/creditcard.csv"
  processed_data_path: "data/processed/"
  sample_data_path: "data/sample/"
  test_size: 0.2
  random_state: 42

# Model Configuration
models:
  isolation_forest:
    contamination: 0.02
    n_estimators: 100
    max_samples: "auto"
    random_state: 42
  
  kmeans:
    min_clusters: 2
    max_clusters: 10
    random_state: 42
    optimize_clusters: true
  
  # Model saving
  save_path: "models/"
  save_models: true
  load_existing: false

# Risk Scoring Configuration
risk_scoring:
  low_risk_threshold: 0.3
  high_risk_threshold: 0.7
  
# Visualization Configuration
visualization:
  output_path: "reports/figures/"
  figure_size: [12, 8]
  dpi: 300
  save_format: "png"
  
# Logging Configuration
logging:
  level: "INFO"
  log_file: "reports/logs/fraud_detection.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5

# Output Configuration
output:
  reports_path: "reports/analysis/"
  generate_summary: true
  generate_visualizations: true
  save_processed_data: true 